name: video_player
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  #UI
  cupertino_icons: ^1.0.8
  auto_size_text: ^3.0.0
  flutter_svg: ^2.0.10+1
  fluttertoast: ^8.2.8

  # Utils
  better_player_plus: ^1.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0


flutter:

  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/